### PR TITLE
a quicker empty check for group by

### PR DESCRIPTION
**Pull request by tgruben**

### CODE REVIEW

**Comment by jaffee** [comment]
is it possible to have a rowSegment that has a bitmap with no containers, or an empty container?

**Comment by tgruben** [comment]
The results of an intersect with no matches is no containers

-Todd

**Comment by tgruben** [comment]
I added another check just to be safe, and a test

**Review by jaffee — COMMENTED** [review]
the case i am concerned about is when the two Rows have bits set in the same shards and containers, but the intersection ends up being 0

**Comment by tgruben** [comment]
that scenario is covered in the test provided, are you wanting it **only** to have bits in the same container?

**Comment by jaffee** [comment]
oh, right, sorry I read that wrong

**Pull request merged**
